name: imdb_app
description: "A new Flutter project."

publish_to: "none" # This is correct, no need to change

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ensure compatibility with Dart 3.x

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
